import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"], // CSS handled by Tailwind CLI (outputs styles.css)
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// Always build to the plugin root: Obsidian loads main.js from there, so a
	// production build that only wrote to dist/ left the installed plugin stale.
	outdir: ".",
	minify: prod,
	loader: {
		".ts": "ts",
		".tsx": "tsx",
		".css": "css",
	},
});

if (prod) {
	await context.rebuild();
	// Mirror the release artifacts into dist/ for uploading to GitHub.
	fs.mkdirSync("dist", { recursive: true });
	for (const file of ["main.js", "manifest.json", "styles.css"]) {
		if (fs.existsSync(file)) fs.copyFileSync(file, `dist/${file}`);
	}
	process.exit(0);
} else {
	await context.watch();
}
